// Generated by CoffeeScript 1.8.0

/**
 * @module mathJS
 * @main mathJS
*
 */

(function() {
  if (typeof DEBUG === "undefined") {
    window.DEBUG = true;
  }

  window.mathJS = {
    Domains: {}
  };

}).call(this);
