// Generated by CoffeeScript 1.9.3

/**
 * @module mathJS
 * @main mathJS
*
 */

(function() {
  var _mathJS, startTime;

  if (typeof DEBUG === "undefined") {
    window.DEBUG = true;
  }

  window.mathJS = {
    Algorithms: {},
    Domains: {},
    Errors: {},
    Geometry: {},
    Operations: {},
    Sets: {},
    Utils: {}
  };

  _mathJS = $.extend({}, mathJS);

  if (DEBUG) {
    window._mathJS = _mathJS;
    startTime = Date.now();
  }

}).call(this);
