// Generated by CoffeeScript 1.9.3
(function() {
  mathJS.Initializer = (function() {
    function Initializer() {}

    Initializer.start = function() {
      return mathJS.Algorithms.ShuntingYard.init();
    };

    return Initializer;

  })();

}).call(this);
