// Generated by CoffeeScript 1.8.0
(function() {
  mathJS.settings = {
    set: {
      maxIterations: 1e3,
      maxMatches: 60
    },
    integral: {
      maxSteps: 1e10
    }
  };

}).call(this);
