// Generated by CoffeeScript 1.9.3
(function() {
  var diff;

  mathJS.Initializer.start();

  if (DEBUG) {
    diff = Date.now() - startTime;
    console.log("time to load mathJS: ", diff, "ms");
    if (diff > 100) {
      console.warn("LOADING TIME CRITICAL!");
    }
  }

}).call(this);
