// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  mathJS.CalculationExceedanceError = (function(_super) {
    __extends(CalculationExceedanceError, _super);

    function CalculationExceedanceError() {
      return CalculationExceedanceError.__super__.constructor.apply(this, arguments);
    }

    return CalculationExceedanceError;

  })(Error);

}).call(this);
