// Generated by CoffeeScript 1.9.3

/**
* Same as a normal Expression with the constraint that only boolean Operations are used.
* @class Expression.Boolean
* @constructor
* @param operation {Operation|String}
* @param expressions... {Expression}
*
 */

(function() {
  mathJS.Expression.Boolean = (function() {
    var CLASS;

    function Boolean() {}

    CLASS = Boolean;

    return Boolean;

  })();

}).call(this);
