// Generated by CoffeeScript 1.8.0
(function() {
  mathJS.Equation = (function() {
    function Equation(term1, term2) {
      this.term1 = term1;
      this.term2 = term2;
    }

    return Equation;

  })();

}).call(this);
