// Generated by CoffeeScript 1.8.0
(function() {
  mathJS.Operation = (function() {
    function Operation(name, precedence, associativity, func, inverse) {
      if (associativity == null) {
        associativity = "left";
      }
      this.name = name;
      this.precedence = precedence;
      this.associativity = associativity;
      this.func = func;
      this.params = func.length;
      this.inverse = inverse || null;
    }

    Operation.prototype.invert = function() {
      if (this.inverse != null) {
        return this.inverse.apply(this, arguments);
      }
      return null;
    };

    return Operation;

  })();

  mathJS.ops = {
    pow: new mathJS.Operation("pow", 1, "right", mathJS.pow, mathJS.root)
  };

}).call(this);
