// Generated by CoffeeScript 1.9.3
(function() {
  mathJS.Relation = (function() {
    function Relation(left, right, operation) {
      if (left.mathEquals(right)) {
        this.left = left;
        this.right = right;
      } else {
        throw new mathJS.Errors.InvalidParametersError("The 2 expressions are not (mathematically) equal!");
      }
    }

    return Relation;

  })();

}).call(this);
