// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  mathJS.Fraction = (function(_super) {
    __extends(Fraction, _super);

    function Fraction(enumerator, denominator) {
      this.enumerator = enumerator;
      this.denominator = denominator;
      Object.defineProperty(this, "value", {
        get: function() {
          return this.enumerator / this.denominator;
        }
      });
    }

    return Fraction;

  })(mathJS.Number);

}).call(this);
