// Generated by CoffeeScript 1.8.0
(function() {
  mathJS.Comparable = (function() {
    function Comparable() {}


    /**
    * This method checks for mathmatical equality. This means new mathJS.Double(4.2).equals(4.2) is true.
    * @method equals
    * @param {Number} n
    * @return {Boolean}
    *
     */

    Comparable.prototype.equals = function(n) {
      throw new Error("To be implemented!");
    };

    Comparable.prototype.e = Comparable.prototype.equals;

    return Comparable;

  })();

}).call(this);
