// Generated by CoffeeScript 1.8.0
(function() {
  mathJS.Parseable = (function() {
    function Parseable() {}

    Parseable.parse = function(str) {
      throw new Error("To be implemented");
    };

    Parseable.prototype.toString = function(args) {
      throw new Error("To be implemented");
    };

    return Parseable;

  })();

}).call(this);
