// Generated by CoffeeScript 1.8.0
(function() {
  mathJS.Poolable = (function() {
    function Poolable() {}

    Poolable._pool = [];

    Poolable.fromPool = function() {
      throw new Error("To be implemented");
    };

    Poolable["new"] = function() {
      if (arguments.length > 0) {
        return this.fromPool.apply(this, arguments);
      }
      return this.fromPool();
    };

    Poolable.prototype.release = function() {
      this.constructor._pool.push(this);
      return this.constructor;
    };

    return Poolable;

  })();

}).call(this);
