// Generated by CoffeeScript 1.9.3
(function() {
  mathJS.Matrix = (function() {
    function Matrix(values) {}

    Matrix.prototype.dimensions = function() {};

    Matrix.prototype.size = function() {};

    Matrix.prototype.rows = function() {};

    Matrix.prototype.columns = function() {};

    Matrix.prototype.cols = function() {};

    return Matrix;

  })();

}).call(this);
