// Generated by CoffeeScript 1.8.0
(function() {
  mathJS.Generator = (function() {
    Generator.newFromGenerators = function(g1, g2) {
      return new mathJS.Generator();
    };

    function Generator(step, offset) {
      this.step = step;
      this.offset = offset;
    }

    return Generator;

  })();

}).call(this);
